### ISSUE TITLE
Missing some OS's icon (Pop_OS)

### ISSUE THREAD

**Issue by antony945** [L4ki/Breeze-Chameleon-Icons#1]
Hi, I love these icons but there is a small problem to which I'd like to find a solution.
I use Pop_OS and I noticed that this theme doesn't provide its icon logo, using Debian's one for it, in notifications and in "about" section of settings ([screen](https://imgur.com/a/dwcVVbi)).
So, is there anything I can do to manually edit that icon and force the system to use Pop_Os's icon instead? Thanks a lot, except this, your icons are fantastic!

**Comment by L4ki** [comment]
Hi antony945, 
I use openSUSE Tumbleweed, Plasma DE.
When I want to change the openSUSE icon to System Information, I do the following: Change the icon found: (usr / share / icons / hicolor / scalable / apps). The icon is named "openSUSE-distributor-logo.svg"
So this icon is not in the icon pack: "Breeze-Chameleon-Icons"

Try to find a solution here: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1730

Greetings,
P.S.
Let us know if you have managed to solve this problem.

**Comment by antony945** [comment]
Sorry for the late reply, I found a simple alternative solution, I edited the "index.theme" file adding "Pop" on the "Inherits" line. This solved the problem for me, great!
![Screenshot from 2020-05-16 09-55-24](https://user-images.githubusercontent.com/22977372/82114186-6fb25e00-975b-11ea-917f-8174838f5542.png)
![Screenshot from 2020-05-16 10-00-00](https://user-images.githubusercontent.com/22977372/82114272-067f1a80-975c-11ea-9a6a-a16dd2caad8e.png)

**Comment by L4ki** [comment]
Great,

I'm glad you did it!

**Comment by calegario** [comment]
Hi antony945, thank you for the tip!
It solves not only the "about" logo, but also some interface icons (in Pop Store, for example).
However, after change that, I had some problems with folder-color nautilus extensions.
So, I modified the entry from `Pop` to `Pop-Extra,pop-os-branding,Adwaita`. It works for me!

> Sorry for the late reply, I found a simple alternative solution, I edited the "index.theme" file adding "Pop" on the "Inherits" line. This solved the problem for me, great!
> ![Screenshot from 2020-05-16 09-55-24](https://user-images.githubusercontent.com/22977372/82114186-6fb25e00-975b-11ea-917f-8174838f5542.png)
> ![Screenshot from 2020-05-16 10-00-00](https://user-images.githubusercontent.com/22977372/82114272-067f1a80-975c-11ea-9a6a-a16dd2caad8e.png)

**Comment by L4ki** [comment]
Hi calegario,

Well done! I am glad that you succeeded and that you shared the solution.

**Comment by vancanhuit** [comment]
The solution that @calegario provided actually works for me. Thanks.
