### ISSUE TITLE
Games folder icon has a different highlight color from other folder icons.

### ISSUE THREAD

**Issue by baduhai** [L4ki/Breeze-Chameleon-Icons#2]
This is present on both light and dark variants of the theme.

![Screenshot_20210904_121728](https://user-images.githubusercontent.com/31864305/132091119-36f4e8ff-c412-4aff-8330-1ebe39cb5478.png)

**Comment by L4ki** [comment]
Hi baduhai,

Yes, I did it on purpose.

But I could change that in the next update.

**Comment by Prayag2** [comment]
Please change it. It looks bad.

**Comment by L4ki** [comment]
Ok, I'll change next week.

**Comment by baduhai** [comment]
Thanks for the change! Things look way more coherent now.

I have one additional suggestion that I didn't feel like it deserved a whole new issue on here. As you might know, in plasma 5.23 there will be a new feature where you are able to change the accent colour of the colour scheme. As far as I know, there has been no accompanying feature to change the accent colour of breeze icons. 

I'm definitely going to be using this icon pack as I think it's the perfect companion for the new feature, but I feel like you could maybe submit a merge request to the original breeze icon pack the implements the chameleon feature. All my interactions with the KDE folks have been great so far, and I'm sure they'd be welcoming of the merge request, and willing to work out any issues that may arise. Plus it's a great way to contribute upstream!

Just a suggestion, think about it.
