### ISSUE TITLE
Some icons messed up when at 48 pixels or smaller size

### ISSUE THREAD

**Issue by pizzadude** [L4ki/Breeze-Chameleon-Icons#4]
Some icons are messed up when at 48 pixels or smaller size. See image below.
Other than that, great icon theme!

https://i.imgur.com/VOUViJ5.png

**Comment by pizzadude** [comment]
@L4ki thanks for updating it!

**Comment by L4ki** [comment]
@pizzadude 

Thank you for alerting me to the problem.
