### ISSUE TITLE
KeePassXC tray icon is not monochrome

### ISSUE THREAD

**Issue by Akselmo** [L4ki/Breeze-Chameleon-Icons#5]
Hi, just a tiny thing, love the icons.

I have set the KeepassXC icon to monochrome in it's settings but it's still colored in the tray. Any way to fix this?

![image](https://user-images.githubusercontent.com/13801236/229354428-336966f0-ce5f-4643-80e4-feba0b952200.png)

Thanks for your hard work!

**Comment by L4ki** [comment]
Hi Akselmo,

It looks like this to me, and so it should be with you: https://postimg.cc/bDdDxqpv

When you set up:  Tray icon type: Monochrome (light), close the KeepassxC app, and then restart it.

Please let me know if you have succeeded,

**Comment by Akselmo** [comment]
Unfortunately didn't work.

I tried to change it to all the possible options, restarting keepassxc in the middle. I also changed the setting to monochrome light, logged out and back in and no change.

When looking at the icon in cuttlefish it also shows only the colored icon (in all sizes):

![image](https://user-images.githubusercontent.com/13801236/229571745-8c8fe0e9-66f1-4f59-a383-4d60b2f57fc1.png)

However if I use the KDE's icon picker it shows right:

![image](https://user-images.githubusercontent.com/13801236/229571884-9274556b-c4ab-493e-90c2-d0c83a1fd9ff.png)

I also installed all the chameleon icon packs but did not work :/

**Comment by L4ki** [comment]
I understand.

OK, for the next update, 06.04. (Saturday) I add "Keepassxc" icons directly to the "Breeze Chameleon Icons" icon package

I've already done. This is what they look like: https://postimg.cc/bZG6LGHX

**Comment by Akselmo** [comment]
Looks great! I'll give it another try at next update then :)

**Comment by Akselmo** [comment]
Hi, I think it's now working! I have both chameleon dark and chameleon dark rounded icon packs installed. Thanks for the update!
